zulip/zilencer/urls.py
from django.conf.urls import url, include
from typing import Any

from zerver.lib.rest import rest_dispatch

import zilencer.views
import zerver.views.report

i18n_urlpatterns = []  # type: Any

# Zilencer views following the REST API style
v1_api_and_json_patterns = [
    url('^deployment/report_error$', rest_dispatch,
        {'POST': 'zerver.views.report.report_error'}),
    url('^remotes/push/register$', rest_dispatch,
        {'POST': 'zilencer.views.remote_server_register_push'}),
    url('^remotes/push/unregister$', rest_dispatch,
        {'POST': 'zilencer.views.remote_server_unregister_push'}),
    url('^remotes/push/notify$', rest_dispatch,
        {'POST': 'zilencer.views.remote_server_notify_push'}),
]

urlpatterns = [
    url(r'^api/v1/', include(v1_api_and_json_patterns)),
    url(r'^json/', include(v1_api_and_json_patterns)),
]

zulip/zproject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView, RedirectView
from django.utils.module_loading import import_string
import os.path
import zerver.forms
from zproject import dev_urls
from zproject.legacy_urls import legacy_urls
from zerver.views.integrations import IntegrationView, APIView, HelpView
from zerver.lib.integrations import WEBHOOK_INTEGRATIONS
from zerver.webhooks import github_dispatcher


from django.contrib.auth.views import (login, password_reset,
                                       password_reset_done, password_reset_confirm, password_reset_complete)

import zerver.tornado.views
import zerver.views
import zerver.views.auth
import zerver.views.compatibility
import zerver.views.home
import zerver.views.email_mirror
import zerver.views.registration
import zerver.views.zephyr
import zerver.views.users
import zerver.views.unsubscribe
import zerver.views.integrations
import zerver.views.user_settings
import zerver.views.muting
import zerver.views.streams
import confirmation.views

from zerver.lib.rest import rest_dispatch

# NB: There are several other pieces of code which route requests by URL:
#
#   - legacy_urls.py contains API endpoint written before the redesign
#     and should not be added to.
#
#   - runtornado.py has its own URL list for Tornado views.  See the
#     invocation of web.Application in that file.
#
#   - The Nginx config knows which URLs to route to Django or Tornado.
#
#   - Likewise for the local dev server in tools/run-dev.py.

# These views serve pages (HTML). As such, their internationalization
# must depend on the url.
#
# If you're adding a new page to the website (as opposed to a new
# endpoint for use by code), you should add it here.
i18n_urls = [
    url(r'^$', zerver.views.home.home, name='zerver.views.home.home'),
    # We have a desktop-specific landing page in case we change our /
    # to not log in in the future. We don't want to require a new
    # desktop app build for everyone in that case
    url(r'^desktop_home/$', zerver.views.home.desktop_home, name='zerver.views.home.desktop_home'),

    url(r'^accounts/login/sso/$', zerver.views.auth.remote_user_sso, name='login-sso'),
    url(r'^accounts/login/jwt/$', zerver.views.auth.remote_user_jwt, name='login-jwt'),
    url(r'^accounts/login/social/(\w+)$', zerver.views.auth.start_social_login, name='login-social'),
    url(r'^accounts/login/google/$', zerver.views.auth.start_google_oauth2, name='zerver.views.auth.start_google_oauth2'),
    url(r'^accounts/login/google/send/$',
        zerver.views.auth.send_oauth_request_to_google,
        name='zerver.views.auth.send_oauth_request_to_google'),
    url(r'^accounts/login/google/done/$', zerver.views.auth.finish_google_oauth2, name='zerver.views.auth.finish_google_oauth2'),
    url(r'^accounts/login/subdomain/$', zerver.views.auth.log_into_subdomain, name='zerver.views.auth.log_into_subdomain'),
    url(r'^accounts/login/local/$', zerver.views.auth.dev_direct_login, name='zerver.views.auth.dev_direct_login'),
    # We have two entries for accounts/login to allow reverses on the Django
    # view we're wrapping to continue to function.
    url(r'^accounts/login/', zerver.views.auth.login_page, {'template_name': 'zerver/login.html'}, name='zerver.views.auth.login_page'),
    url(r'^accounts/login/', login, {'template_name': 'zerver/login.html'},
        name='django.contrib.auth.views.login'),
    url(r'^accounts/logout/', zerver.views.auth.logout_then_login, name='zerver.views.auth.logout_then_login'),

    url(r'^accounts/webathena_kerberos_login/',
        zerver.views.zephyr.webathena_kerberos_login,
        name='zerver.views.zephyr.webathena_kerberos_login'),

    url(r'^accounts/password/reset/$', password_reset,
        {'post_reset_redirect': '/accounts/password/reset/done/',
         'template_name': 'zerver/reset.html',
         'email_template_name': 'zerver/emails/password_reset.txt',
         'subject_template_name': 'zerver/emails/password_reset.subject',
         'password_reset_form': zerver.forms.ZulipPasswordResetForm,
         }, name='django.contrib.auth.views.password_reset'),
    url(r'^accounts/password/reset/done/$', password_reset_done,
        {'template_name': 'zerver/reset_emailed.html'}),
    url(r'^accounts/password/reset/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'post_reset_redirect': '/accounts/password/done/',
         'template_name': 'zerver/reset_confirm.html',
         'set_password_form': zerver.forms.LoggingSetPasswordForm},
        name='django.contrib.auth.views.password_reset_confirm'),
    url(r'^accounts/password/done/$', password_reset_complete,
        {'template_name': 'zerver/reset_done.html'}),

    # Avatar
    url(r'^avatar/(?P<email_or_id>[\S]+)?/(?P<medium>[\S]+)?', zerver.views.users.avatar, name='zerver.views.users.avatar'),
    url(r'^avatar/(?P<email_or_id>[\S]+)?', zerver.views.users.avatar, name='zerver.views.users.avatar'),

    # Registration views, require a confirmation ID.
    url(r'^accounts/register/social/(\w+)$',
        zerver.views.auth.start_social_signup,
        name='signup-social'),
    url(r'^accounts/home/', zerver.views.registration.accounts_home,
        name='zerver.views.registration.accounts_home'),
    url(r'^accounts/send_confirm/(?P<email>[\S]+)?',
        TemplateView.as_view(template_name='zerver/accounts_send_confirm.html'), name='send_confirm'),
    url(r'^accounts/register/', zerver.views.registration.accounts_register,
        name='zerver.views.registration.accounts_register'),
    url(r'^accounts/do_confirm/(?P<confirmation_key>[\w]+)', confirmation.views.confirm, name='confirmation.views.confirm'),

    url(r'^accounts/confirm_new_email/(?P<confirmation_key>[\w]+)',
        zerver.views.user_settings.confirm_email_change,
        name='zerver.views.user_settings.confirm_email_change'),

    # Email unsubscription endpoint. Allows for unsubscribing from various types of emails,
    # including the welcome emails (day 1 & 2), missed PMs, etc.
    url(r'^accounts/unsubscribe/(?P<type>[\w]+)/(?P<token>[\w]+)',
        zerver.views.unsubscribe.email_unsubscribe, name='zerver.views.unsubscribe.email_unsubscribe'),

    # Portico-styled page used to provide email confirmation of terms acceptance.
    url(r'^accounts/accept_terms/$', zerver.views.home.accounts_accept_terms, name='zerver.views.home.accounts_accept_terms'),

    # Realm Creation
    url(r'^create_realm/$', zerver.views.registration.create_realm, name='zerver.views.create_realm'),
    url(r'^create_realm/(?P<creation_key>[\w]+)$', zerver.views.registration.create_realm, name='zerver.views.create_realm'),

    # Login/registration
    url(r'^register/$', zerver.views.registration.accounts_home, name='register'),
    url(r'^login/$', zerver.views.auth.login_page, {'template_name': 'zerver/login.html'}, name='zerver.views.auth.login_page'),

    # A registration page that passes through the Realm.string_id, for totally open realms.
    url(r'^register/(?P<realm_str>\S+)/$', zerver.views.registration.accounts_home_with_realm_str,
        name='zerver.views.registration.accounts_home_with_realm_str'),

    # API and integrations documentation
    url(r'^api/$', APIView.as_view(template_name='zerver/api.html')),
    url(r'^api/endpoints/$', zerver.views.integrations.api_endpoint_docs, name='zerver.views.integrations.api_endpoint_docs'),
    url(r'^integrations/$', IntegrationView.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name='zerver/about.html')),
    url(r'^apps/$', TemplateView.as_view(template_name='zerver/apps.html')),

    url(r'^robots\.txt$', RedirectView.as_view(url='/static/robots.txt', permanent=True)),

    # Landing page, features pages, signup form, etc.
    url(r'^hello/$', TemplateView.as_view(template_name='zerver/hello.html'), name='landing-page'),
    url(r'^new-user/$', RedirectView.as_view(url='/hello', permanent=True)),
    url(r'^features/$', TemplateView.as_view(template_name='zerver/features.html')),
    url(r'^find_my_team/$', zerver.views.registration.find_my_team, name='zerver.views.registration.find_my_team'),
    url(r'^authors/$', zerver.views.users.authors_view, name='zerver.views.users.authors_view'),

    # Terms of service and privacy pages.
    url(r'^terms/$', TemplateView.as_view(template_name='zerver/terms.html'), name='terms'),
    url(r'^privacy/$', TemplateView.as_view(template_name='zerver/privacy.html'), name='privacy'),
]

# Make a copy of i18n_urls so that they appear without prefix for english
urls = list(i18n_urls)

# These endpoints constitute the redesigned API (V1), which uses:
# * REST verbs
# * Basic auth (username:password is email:apiKey)
# * Take and return json-formatted data
#
# If you're adding a new endpoint to the code that requires authentication,
# please add it here.
# See rest_dispatch in zerver.lib.rest for an explanation of auth methods used
#
# All of these paths are accessed by either a /json or /api/v1 prefix
v1_api_and_json_patterns = [
    # realm-level calls
    url(r'^realm$', rest_dispatch,
        {'PATCH': 'zerver.views.realm.update_realm'}),

    # Returns a 204, used by desktop app to verify connectivity status
    url(r'generate_204$', zerver.views.registration.generate_204, name='zerver.views.registration.generate_204'),

    # realm/domains -> zerver.views.realm_domains
    url(r'^realm/domains$', rest_dispatch,
        {'GET': 'zerver.views.realm_domains.list_realm_domains',
         'POST': 'zerver.views.realm_domains.create_realm_domain'}),
    url(r'^realm/domains/(?P<domain>\S+)$', rest_dispatch,
        {'PATCH': 'zerver.views.realm_domains.patch_realm_domain',
         'DELETE': 'zerver.views.realm_domains.delete_realm_domain'}),

    # realm/emoji -> zerver.views.realm_emoji
    url(r'^realm/emoji$', rest_dispatch,

zulip/zilencer/forms.py
from django import forms

class EnterpriseToSForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    company = forms.CharField(max_length=100)
    terms = forms.BooleanField(required=True)

zulip/zerver/tornado/views.py
from __future__ import absolute_import

from django.utils.translation import ugettext as _
from django.http import HttpRequest, HttpResponse

from zerver.models import get_client, UserProfile, Client

from zerver.decorator import asynchronous, \
    authenticated_json_post_view, internal_notify_view, RespondAsynchronously, \
    has_request_variables, REQ, _RespondAsynchronously

from zerver.lib.response import json_success, json_error
from zerver.lib.validator import check_bool, check_list, check_string
from zerver.tornado.event_queue import get_client_descriptor, \
    process_notification, fetch_events
from django.core.handlers.base import BaseHandler

from typing import Union, Optional, Iterable, Sequence, List, Text
import time
import ujson

@internal_notify_view(True)
def notify(request):
    # type: (HttpRequest) -> HttpResponse
    process_notification(ujson.loads(request.POST['data']))
    return json_success()

@has_request_variables
def cleanup_event_queue(request, user_profile, queue_id=REQ()):
    # type: (HttpRequest, UserProfile, Text) -> HttpResponse
    client = get_client_descriptor(str(queue_id))
    if client is None:
        return json_error(_("Bad event queue id: %s") % (queue_id,))
    if user_profile.id != client.user_profile_id:
        return json_error(_("You are not authorized to access this queue"))
    request._log_data['extra'] = "[%s]" % (queue_id,)
    client.cleanup()
    return json_success()

@asynchronous
@has_request_variables
def get_events_backend(request, user_profile, handler,
                       user_client = REQ(converter=get_client, default=None),
                       last_event_id = REQ(converter=int, default=None),
                       queue_id = REQ(default=None),
                       apply_markdown = REQ(default=False, validator=check_bool),
                       all_public_streams = REQ(default=False, validator=check_bool),
                       event_types = REQ(default=None, validator=check_list(check_string)),
                       dont_block = REQ(default=False, validator=check_bool),
                       narrow = REQ(default=[], validator=check_list(None)),
                       lifespan_secs = REQ(default=0, converter=int)):
    # type: (HttpRequest, UserProfile, BaseHandler, Optional[Client], Optional[int], Optional[List[Text]], bool, bool, Optional[Text], bool, Iterable[Sequence[Text]], int) -> Union[HttpResponse, _RespondAsynchronously]
    if user_client is None:
        user_client = request.client

    events_query = dict(
        user_profile_id = user_profile.id,
        user_profile_email = user_profile.email,
        queue_id = queue_id,
        last_event_id = last_event_id,
        event_types = event_types,
        client_type_name = user_client.name,
        all_public_streams = all_public_streams,
        lifespan_secs = lifespan_secs,
        narrow = narrow,
        dont_block = dont_block,
        handler_id = handler.handler_id)

    if queue_id is None:
        events_query['new_queue_data'] = dict(
            user_profile_id = user_profile.id,
            realm_id = user_profile.realm_id,
            user_profile_email = user_profile.email,
            event_types = event_types,
            client_type_name = user_client.name,
            apply_markdown = apply_markdown,
            all_public_streams = all_public_streams,
            queue_timeout = lifespan_secs,
            last_connection_time = time.time(),
            narrow = narrow)

    result = fetch_events(events_query)
    if "extra_log_data" in result:
        request._log_data['extra'] = result["extra_log_data"]

    if result["type"] == "async":
        handler._request = request
        return RespondAsynchronously
    if result["type"] == "error":
        return json_error(result["message"])
    return json_success(result["response"])

zulip/zerver/views/alert_words.py
from __future__ import absolute_import

from django.http import HttpResponse, HttpRequest

from typing import List
from zerver.models import UserProfile

from zerver.decorator import has_request_variables, REQ
from zerver.lib.response import json_success
from zerver.lib.validator import check_list, check_string

from zerver.lib.actions import do_add_alert_words, do_remove_alert_words, do_set_alert_words
from zerver.lib.alert_words import user_alert_words

from typing import Text

def list_alert_words(request, user_profile):
    # type: (HttpRequest, UserProfile) -> HttpResponse
    return json_success({'alert_words': user_alert_words(user_profile)})

def clean_alert_words(alert_words):
    # type: (List[Text]) -> List[Text]
    alert_words = [w.strip() for w in alert_words]
    return [w for w in alert_words if w != ""]

@has_request_variables
def set_alert_words(request, user_profile,
                    alert_words=REQ(validator=check_list(check_string), default=[])):
    # type: (HttpRequest, UserProfile, List[Text]) -> HttpResponse
    do_set_alert_words(user_profile, clean_alert_words(alert_words))
    return json_success()

@has_request_variables
def add_alert_words(request, user_profile,
                    alert_words=REQ(validator=check_list(check_string), default=[])):
    # type: (HttpRequest, UserProfile, List[Text]) -> HttpResponse
    do_set_alert_words(user_profile, clean_alert_words(alert_words))
    return json_success()

@has_request_variables
def remove_alert_words(request, user_profile,
                       alert_words=REQ(validator=check_list(check_string), default=[])):
    # type: (HttpRequest, UserProfile, List[Text]) -> HttpResponse
    do_remove_alert_words(user_profile, alert_words)
    return json_success()

zulip/zerver/views/attachments.py
from __future__ import absolute_import
from django.http import HttpRequest, HttpResponse

from zerver.decorator import REQ
from zerver.models import UserProfile
from zerver.lib.validator import check_int
from zerver.lib.response import json_success
from zerver.lib.attachments import user_attachments, remove_attachment, \
    access_attachment_by_id


def list_by_user(request, user_profile):
    # type: (HttpRequest, UserProfile) -> HttpResponse
    return json_success({"attachments": user_attachments(user_profile)})


def remove(request, user_profile, attachment_id=REQ(validator=check_int)):
    # type: (HttpRequest, UserProfile, int) -> HttpResponse
    attachment = access_attachment_by_id(user_profile, attachment_id,
                                         needs_owner=True)
    remove_attachment(user_profile, attachment)
    return json_success()

zulip/templates/zerver/api_endpoints.html
{% extends "zerver/portico.html" %}

{# API information page #}

{% block customhead %}
{{ super() }}
{{ minified_js('api')|safe }}
{% endblock %}


{% block portico_content %}
    <h1 class="api-page-header">API endpoints documentation</h1>

    <p>In addition to our <a href="/api">pre-built API bindings for
        Python</a>, we also have
        a <a href="http://en.wikipedia.org/wiki/Representational_state_transfer">REST-ful</a>
    web API.</p>

    <ul class="nav nav-tabs" id="api-example-tabs">
        <li class="active"><a href="#curl" data-toggle="tab" data-class="curl">curl</a></li>
        <li><a href="#python" data-toggle="tab" data-class="python">Python</a></li>
    </ul>

    {% autoescape off %}
        {% for blurb in content %}
        <div class="api-block">
            <h2 class="call">{{ blurb.call }}</h2>
            <div class="endpoint"><code>{{blurb.method}} {{ blurb.endpoint }}</code></div>
            <div class="api-details">
                <h3>Arguments</h3>
                <dl class="dl-horizontal arguments">
                    {% for argument in blurb.arguments %}
                    <dt><code>{{ argument.0 }}</code></dt>
                    <dd>{{ argument.1 }}</dd>
                    {% endfor %}
                </dl>

                <h3>Return values</h3>
                <dl class="dl-horizontal returns">
                    {% for return in blurb.returns %}
                    <dt><code>{{ return.0 }}</code></dt>
                    <dd>{{ return.1 }}</dd>
                    {% endfor %}
                </dl>

                {% if blurb.example_request %}
                    <h3>Example request</h3>
                    {% for lang, req in blurb.example_request.items() %}
                    <div class="example_request {{ lang }}">
                        {{ req }}
                    </div>
                    {% endfor %}
                {% endif %}

                {% if blurb.rendered_response %}
                <h3>Example response</h3>
                <div class="example_response">
                    {{ blurb.rendered_response }}
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    {% endautoescape %}
{% endblock %}

zulip/templates/zerver/bankruptcy.html
<div class="modal hide" id="bankruptcy" tabindex="-1" role="dialog"
    aria-labelledby="bankruptcy-label" aria-hidden="true">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="bankruptcy-label">{{ _('Welcome back') }}</h3>
    </div>

    <div id="bankruptcy-unread-count"></div>

    <div class="modal-footer">
        <button id="yes-bankrupt" class="bankruptcy_button btn btn-primary"
                aria-hidden="true">{{ _('Yes, please!') }}</button>
        <button id="no-bankrupt" class="bankruptcy_button btn btn-default"
                data-dismiss="modal" aria-hidden="true">{{ _("No, I'll catch up.") }}</button>
    </div>
</div>

zulip/templates/zerver/portico_signup.html
{% extends "zerver/portico.html" %}

{# Portico page with signup code #}

{% block customhead %}
{{ super() }}
{{ minified_js('signup')|safe }}
{% endblock %}

zulip/templates/zerver/register.html
{% extends "zerver/portico_signup.html" %}
{#
Gather other user information, after having confirmed
their email address.

Form is validated both client-side using jquery-validate (see signup.js) and server-side.
#}

{% block customhead %}
{{ super() }}
{{ minified_js('zxcvbn')|safe }}
{% endblock %}

{% block portico_content %}
<div class="register-account flex full-page">
  <div class="bg-image"></div>
  <div class="center-block new-style" style="padding: 20px 0px">
    <div class="pitch">
        {% trans %}
        <h1>You're almost there.</h1>
        <p>
          We just need you to do one last thing.
        </p>
        {% endtrans %}
    </div>

    <form method="post" class="form-horizontal white-box" id="registration" action="{{ url('zerver.views.registration.accounts_register') }}">
    {{ csrf_input }}
        <div class="input-box no-validation">
            <input type='hidden' name='key' value='{{ key }}' />
            <input type='hidden' name='timezone' id='timezone'/>
            <input id="id_email" type='text' disabled="true" placeholder="{{ email }}" required />
            <label for="id_email" class="inline-block label-title">{{ _('Email') }}</label>
            <div class="required"></div>
            <img class="valid" src="/static/images/checkbox-valid.svg" alt="{{ _('Valid') }}" />
        </div>

        <div class="input-box">
            {% if lock_name %}
                <p class="fakecontrol">{{ full_name }}</p>
            {% else %}
                <input id="id_full_name" class="required" type="text" name="full_name"
                value="{% if full_name %}{{ full_name }}{% elif form.full_name.value() %}{{ form.full_name.value() }}{% endif %}"
                maxlength={{ MAX_NAME_LENGTH }} required />
                {% if form.full_name.errors %}
                    {% for error in form.full_name.errors %}
                        <div class="help-inline text-error">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            {% endif %}
            <label for="id_full_name" class="inline-block label-title">{{ _('Full name') }}</label>
            <div class="required"></div>
            <img class="valid" src="/static/images/checkbox-valid.svg" alt="{{ _('Valid') }}" />
        </div>

        <div class="input-box full-width">
            <div class="help-box">
                {{ _('Zulip has full unicode support, so you can spell your name exactly how you want it to appear.') }}
            </div>
        </div>

        {% if password_auth_enabled %}
        <div class="input-box">
            <input id="id_password" class="required" type="password" name="password"
                   value="{% if form.password.value() %}{{ form.password.value() }}{% endif %}"
                   maxlength={{ MAX_PASSWORD_LENGTH }}
                   data-min-length="{{password_min_length}}"
                   data-min-quality="{{password_min_quality}}" required />
            <label for="id_password" class="inline-block">{{ _('Password') }}</label>
            <div class="required"></div>
            <img class="valid" src="/static/images/checkbox-valid.svg" alt="{{ _('Valid') }}" />
            {% if full_name %}
            <span class="help-inline">
              {{ _('This is used for mobile applications and other tools that require a password.') }}
            </span>
            {% endif %}
            {% if form.password.errors %}
            {% for error in form.password.errors %}
            <div class="help-inline text-error">{{ error }}</div>
            {% endfor %}
            {% endif %}

            <div class="progress" id="pw_strength" title="{{ _('Password strength') }}">
                <div class="bar bar-danger" style="width: 10%;"></div>
            </div>
        </div>
        {% endif %}

        {% if creating_new_team %}
        <div class="input-box">
            <div class="inline-block relative">
                <input id="id_team_name" class="required" type="text"
                    placeholder="Acme"
                    value="{% if form.realm_name.value() %}{{ form.realm_name.value() }}{% endif %}"
                    name="realm_name" maxlength={{ MAX_REALM_NAME_LENGTH }} required />
                    {% if form.realm_name.errors %}
                        {% for error in form.realm_name.errors %}
                            <div class="help-inline text-error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                <div class="required"></div>
                <img class="valid" src="/static/images/checkbox-valid.svg" alt="{{ _('Valid') }}" />
            </div>
            <label for="id_team_name" class="inline-block label-title">{{ _('Organization name') }}</label>

            <div class="help-box margin-top">
                {{ _('This can be changed later on the settings page.') }}
            </div>
        </div>

        <div class="input-box">
            <label for="id_team_subdomain" class="inline-block label-title">
                {% if realms_have_subdomains %}
                    {{ _('Subdomain') }}
                {% else %}
                    {{ _('Short name') }}
                {% endif %}
            </label>
            <div class="breakpoint">
                <div class="inline-block relative">
                    <input id="id_team_subdomain" class="required" type="text"
                        placeholder="acme"
                        value="{% if form.realm_subdomain.value() %}{{ form.realm_subdomain.value() }}{% endif %}"
                        name="realm_subdomain" maxlength={{ MAX_REALM_SUBDOMAIN_LENGTH }} required />
                    <div class="required"></div>
                    <img class="valid" src="/static/images/checkbox-valid.svg" alt="{{ _('Valid') }}" />
                </div>
                {% if realms_have_subdomains %}
                <div class="inline-block external-host"> .{{ external_host }}</div>
                {% endif %}
                    {% if form.realm_subdomain.errors %}
                        {% for error in form.realm_subdomain.errors %}
                            <div class="help-inline text-error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
            </div>
            <div class="help-box margin-top">
                {% if realms_have_subdomains %}
                    {{ _("The address you'll use to sign in to your organization.") }}
                {% else %}
                    {{ _("A short, unique name for your organization, with no spaces.") }}
                {% endif %}
            </div>
        </div>

        <div class="input-group m-10 inline-block">
          <label for="id_org_type" class="label-title">{{ _('Organization type') }}</label>

          {% for org_type_value, org_type_text in form.realm_org_type.field.choices %}
          <div class="input-group radio">
            <input id="id_radio_{{ org_type_value }}" class="required inline-block" type="radio"
                name="realm_org_type" value="{{ org_type_value }}"
                {% if org_type_value|string == form.realm_org_type.value()|string %} checked {% endif %} />
            <label for="id_radio_{{ org_type_value }}" class="inline-block">{{ org_type_text }}</label>
          </div>
          {% endfor %}
        </div>
        <div class="m-10">
          <div class="help-box">
            <div id="org_type_blob_1" class="blob display-none">
              {% trans %}
              Create a corporate organization if your users will be members of the
              same company, where the privacy expectation is that the company's
              organization administrators may need to have access to your users'
              private message history. Zulip features that allow organization
              administrators to take control of accounts or access private message
              history for other users are only available to corporate organizations.
              {% endtrans %}
            </div>
            <div id="org_type_blob_2" class="blob">
              {% trans %}
              Create a community organization for an open source project, social
              group, or other community where the privacy expectation is that you
              and other organization administrators won't have access to your users'
              private message history. Zulip features that allow organization
              administrators to take control of accounts or access private message
              history for other users are disabled in community organizations.
              {% endtrans %}
            </div>
          </div>
        </div>
        {% endif %}

        <div class="input-group margin terms-of-service">
            {% if terms_of_service %}
            <div class="input-group">
                {#
                This is somewhat subtle.
                Checkboxes have a name and value, and when the checkbox is ticked, the form posts
                with name=value. If the checkbox is unticked, the field just isn't present at all.

                This is distinct from 'checked', which determines whether the checkbox appears
                at all. (So, it's not symmetric to the code above.)
                #}
                <input id="id_terms" class="required" type="checkbox" name="terms"
                       {% if form.terms.value() %}checked="checked"{% endif %} />
                <label for="id_terms" class="inline-block">
                  {% trans %}I agree to the <a href="{{ server_uri }}/terms" target="_blank">Terms of Service</a>.{% endtrans %}
                </label>
                {% if form.terms.errors %}
                    {% for error in form.terms.errors %}
                        <div class="help-inline text-error">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
            {% endif %}
            <div class="submit-button-box m-10">
                <button type="submit">{{ _('Register') }}</button>
                <input type="hidden" name="next" value="{{ next }}" />
            </div>
        </div>
    </form>
  </div>
</div>

<script type="text/javascript">
if ($('#id_email:visible').length) {
    autofocus('#id_email');
} else if ($('#id_full_name:visible').length) {
    autofocus('#id_full_name');
}

$("[name=realm_org_type]").on("change", function () {
    $(".blob").hide();
    $("#org_type_blob_" + this.value).show();
});

$("#timezone").val(moment.tz.guess());
</script>

{% endblock %}

zulip/templates/zerver/subscriptions.html
{# Streams management tab of the app. #}
<div class="subscriptions">
    <div id="subscriptions_table">
    </div>
</div>